export const defaults = {
    newSchool:{
        __typename:"NewSchool",
        id:"",
        name:"",
    },
    newMajor:{
        __typename:"NewMajor",
        id:"",
        name:"",
    },
    searchNewMajor:{
        __typename:"NewMajor",
        id:"",
        name:"",
    },
    searchNewUniversity:{
        __typename:"NewSchool",
        id:"",
        name:"",
    },
    newGradeAndClasses:[]
  };