export const defaults = {
    newSchool:{
        __typename:"NewSchool",
        id:"",
        name:"",
    },
    newMajor:{
        __typename:"NewMajor",
        id:"",
        name:"",
    },
    searchNewMajor:{
        __typename:"NewMajor",
        id:"",
        name:"",
    },
    searchNewUniversity:{
        __typename:"NewSchool",
        id:"",
        name:"",
    },
    me:{
        __typename:"User",
        id:"",
        name:"",
        username:"",
    },
    newUnreadMessages:[],
    newGradeAndClasses:[],
    getMessages:[],
    classGroupMessages:[],
    workGroupMessage:[],
    familyGroupMessage:[],
    locationGroupMessages:[],
    regStatusMessages:[],

  };